#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
H=0

while [ $H -le 12 ]
do
    m=1
    echo Hour: $H
    while [ $m -le 59 ]
    do
        echo $m
        ((m++))
    done
    ((H++))
done